### ISSUE TITLE
phpstan not running

### ISSUE THREAD

**Issue by SebSept** [friends-of-presta/fop_console#34]
```
» _PS_ROOT_DIR_=/a/prestashop/install php vendor/bin/phpstan analyse src --configuration tests/phpstan/phpstan.neon                 seb@localhost
PHP Fatal error:  Uncaught Error: Call to undefined method PhpParser\Node\Name::toLowerString() in phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:560
Stack trace:
#0 phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php(624): PhpParser\ParserAbstract->handleBuiltinTypes(Object(PhpParser\Node\Name))
#1 phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(238): PhpParser\Parser\Php7->PhpParser\Parser\{closure}(16)
#2 phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(142): PhpParser\ParserAbstract->doParse()
#3 phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/src/Parser/DirectParser.php(35): PhpParser\ParserAbstract->parse('<?php\n\n/**\n * @...', Object(PhpParser\ErrorHandler\Collecting))
#4 phar:///home/seb/dev/php/fop_co in phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 560

Fatal error: Uncaught Error: Call to undefined method PhpParser\Node\Name::toLowerString() in phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php:560
Stack trace:
#0 phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/Parser/Php7.php(624): PhpParser\ParserAbstract->handleBuiltinTypes(Object(PhpParser\Node\Name))
#1 phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(238): PhpParser\Parser\Php7->PhpParser\Parser\{closure}(16)
#2 phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php(142): PhpParser\ParserAbstract->doParse()
#3 phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/src/Parser/DirectParser.php(35): PhpParser\ParserAbstract->parse('<?php\n\n/**\n * @...', Object(PhpParser\ErrorHandler\Collecting))
#4 phar:///home/seb/dev/php/fop_co in phar:///home/seb/dev/php/fop_console/vendor/phpstan/phpstan/phpstan/vendor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 560
```

**Comment by SebSept** [comment]
nikic/php-parser 3.1.5 throw that error.
[It is outdated.](https://github.com/friends-of-presta/fop_console/blob/master/composer.lock#L336)
It is [required by prestashop/php-dev-tools](prestashop/php-dev-tools).

**Comment by SebSept** [comment]
Without prestashop/php-dev-tools there is other errors.
Seems not so simple to make it run :/
I tried with phpstan as a dependency or as a global package, no changes.

Do you have it running ?

**Comment by zalexki** [comment]
yes it's running on https://github.com/PrestaShopCorp/ps_checkout with docker but you should try implementing as a github action (should be copy paste) and remove it from composer dependencies
